server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:txn_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.hbm2ddl.auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console.enabled: true

rewardPoint:
  onePointRange: 50
  twoPointsRange: 100
  monthCount: 3








